Creation of the Neural Net Builder
spookieoli/VreeDB pull request #32
Opened 2024-04-27 05:03 UTC by RamBITS-AI

Creating the Neural Net Builder.

2024-04-27 17:16 UTC, spookieoli commented on templates/index.gohtml
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/components/icon.min.css" integrity="sha512-rTyypI20S663Wq9zrzMSOP1MNPHaYX7+ug5OZ/DTqCDLwRdErCo2W30Hdme3aUzJSv
we have semantic under static/ please add the file to the static folder

2024-04-27 17:19 UTC, spookieoli requested changes
will add some response from neural net, please add the semanticui file to the static folder so we can load it from a trusted source - even if we are on a isolated on premise location

2024-04-27 17:23 UTC, spookieoli commented on templates/index.gohtml
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/components/icon.min.css" integrity="sha512-rTyypI20S663Wq9zrzMSOP1MNPHaYX7+ug5OZ/DTqCDLwRdErCo2W30Hdme3aUzJSv
added the file

2024-04-27 17:27 UTC, spookieoli approved these changes

2024-04-27 20:27 UTC, spookieoli commented
Added changes to js to get updates from Trainingprogress every second, this is ready for testing

2024-04-27 22:13 UTC, RamBITS-AI commented on templates/neuralnetbuilder.gohtml
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/components/icon.min.css" integrity="sha512-rTyypI20S663Wq9zrzMSOP1MNPHaYX7+ug5OZ/DTqCDLwRdErCo2W30Hdme3aUzJSv
There is one here as well.
```suggestion
    <link rel="stylesheet" href="/static/icon.min.css"/>
```

2024-04-28 14:32 UTC, spookieoli approved these changes
Great Work!

2024-04-28 14:44 UTC, merged